version: 2.1
jobs:
  build_apk:
    docker:
      - image: cimg/android:2024.03 # سيرفر أندرويد جاهز ومحدث بالكامل
    steps:
      - checkout
      - run:
          name: Unzip Project Files
          command: |
            echo "جاري فك ضغط ملفات المشروع..."
            unzip -o *.zip
            
            # التأكد من نقل الملفات للمجلد الرئيسي إذا كانت مستخرجة داخل مجلد فرعي
            if [ ! -f "build.gradle.kts" ] && [ ! -f "build.gradle" ]; then
              subfolder=$(find . -maxdepth 2 -name "build.gradle*" -exec dirname {} \;)
              if [ -n "$subfolder" ] && [ "$subfolder" != "." ]; then
                echo "تم العثور على المجلد الفرعي ونقل الملفات: $subfolder"
                cp -r $subfolder/* .
              fi
            fi
      - run:
          name: Build Android APK
          command: |
            if [ -f "gradlew" ]; then
              chmod +x gradlew
              ./gradlew assembleDebug
            else
              echo "ملف gradlew مفقود، يتم تشغيل البناء عبر الـ Wrapper الداخلي للمشروع..."
              java -cp gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain assembleDebug
            fi
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks

workflows:
  version: 2
  build:
    jobs:
      - build_apk
